### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by gabriel-maxx** [Tserith/Parasite#2]
hello I'm having an error compiling the project could you help me?

Build started...
1>------ Build started: Project: Driver, Configuration: Release x64 ------
1>Building 'Driver' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>entry.cpp
1>Driver.vcxproj -> C:\Users\Kevin\Documents\Parasite-master\x64\Release\Driver.sys
1>Done Adding Additional Store
1>Successfully signed: C:\Users\Kevin\Documents\Parasite-master\x64\Release\Driver.sys
1>
1>Inf2Cat task was skipped as there were no inf files to process
2>------ Build started: Project: Parasite, Configuration: Release x64 ------
2>'make' não é reconhecido como um comando interno
2>ou externo, um programa operável ou um arquivo em lotes.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: The command "python file2array.py C:\Users\Kevin\Documents\Parasite-master\x64\Release\Driver.sys driver.h
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: cd bootkit
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: make
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(145,5): error MSB3073: :VCEnd" exited with code 9009.
2>Done building project "Parasite.vcxproj" -- FAILED.
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by Tserith** [comment]
Python and Make must both be installed and accessible from the Windows PATH environment variable to build the project.

**Comment by gabriel-maxx** [comment]
> Python and Make must both be installed and accessible from the Windows PATH environment variable to build the project.

i installed python 3xx but as for make what do i have to install exactly MinGW?

**Comment by Tserith** [comment]
MinGW should work, but you will need to rename or copy mingw32-make.exe to make.exe

This may be relavent https://stackoverflow.com/questions/54742271/how-to-compile-code-with-a-makefile-in-windows-command-prompt-using-mingw-compil

**Comment by gabriel-maxx** [comment]
> MinGW should work, but you will need to rename or copy mingw32-make.exe to make.exe
> 
> This may be relavent https://stackoverflow.com/questions/54742271/how-to-compile-code-with-a-makefile-in-windows-command-prompt-using-mingw-compil

thanks
